### PR TITLE
Service Calendar + Turbo Like button

### PR DESCRIPTION
**Pull request by EvanBurriola**
Refactored calendar to support a service account that is configured in our Google Cloud Platform. All credentials verified and current display calendar is my local tester 'Embed Example'. It should be very easily portable to S&S calendar. Additionally, beginning implementation of Turbo Links on the announcement like button. Still need to configure linking order, can sometimes turbo refresh before the database updates causing a 'nonresponsive' looking click.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by justinchai1 — APPROVED** [review]
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**Review by victoriapham1 — APPROVED** [review]
# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

**Review by bernardo-gdc — APPROVED** [review]
Good changes, code seems alot more intuitive, plus comments really help as well. We will have to look into testing google calendar's api in the future.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

**Comment by justinchai1** [comment]
LGTM! add test in the test branch!

**Pull request merged**
