### PR TITLE
Role distinction

### PR DESCRIPTION
**Pull request by EvanBurriola**
# Description

Creates the role distinction between Officers and standard Members. This blocks members from visiting certain URL's as well as conditionally rendering certain actions (CRUD / Nav bar access) to display for only officers rather than standard members.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by victoriapham1 — CHANGES_REQUESTED** [review]
This feature is currently not working.

**Comment by EvanBurriola** [comment]
The brakeman is still failing currently, I'll review the failure when I can and most likely be able to add an ignore if needed.

**Comment by victoriapham1** [comment]
Please also include comments that describe your work and write tests for this feature.

**Review by victoriapham1 — CHANGES_REQUESTED** [review]
Please add comments and run Rubocop.

**Comment by bernardo-gdc** [comment]
All these changes look good to me and passes RSpec

**Review by bernardo-gdc — APPROVED** [review]
all comments look good, definitely easier to tell what is going on!

**Comment by EvanBurriola** [comment]
role-distinctionPRrubocopINIT
role-distinctionPRrubocopPOST

**Review by victoriapham1 — APPROVED** [review]
# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

**Pull request merged**
